import { Providers } from '@/provider'
import { i_children } from '@/types/ReactTypes'
import type { Metadata } from 'next'
// import 'node_modules/animate.css/animate.css'

// import Alert from '@/ui/alert'
import '../assets/scss/main.scss'
import './globals.css'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: i_children) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>

        {/* <Alert /> */}
      </body>
    </html>
  )
}
